### ISSUE TITLE
Relation to HTTP Alt-Svc headers and certificate subjects

### ISSUE THREAD

**Issue by Saklad5** [bemasc/svcb-dane#5]
https://github.com/bemasc/svcb-dane/blob/6e945bef3591b06355327f17117aec4169db1cc6/draft-rebs-dnsop-svcb-dane.md?plain=1#L67

If I understand this draft correctly, that means that the client following a PKIX-EE record does **not** ask for a certificate with the name of the origin, but instead asks for a certificate with the name of the endpoint.

Does this mean that a DANE-compatible client will require distinct certificates depending on whether they use Alt-Svc or HTTPS records to locate the endpoint?

---

Consider the following (DNSSEC-validated) records:

```DNS
endpoint.example.               86400	IN	AAAA	2001:db8::
_443._tcp.endpoint.example.	86400	IN	TLSA	1 1 1 [endpoint keys]
origin.example.                 86400	IN	AAAA	2001:db8::1
origin.example.		        86400	IN	HTTPS	1 endpoint.example.
_443._tcp.origin.example.	86400	IN	TLSA	1 1 1 [origin keys]
```

A client that does not support HTTPS records might connect to `origin.example` directly, using an SNI of `origin.example` and comparing it to the TLSA record at `_443._tcp.origin.example`. The response could include the header `Alt-Svc: http/1.1="endpoint.example.com:443"`.

A subsequent request might be directed at `endpoint.example`, with the same SNI and TLSA record (based on [RFC 7838](https://www.rfc-editor.org/info/rfc7838)). Thus, no certificate for `endpoint.example` is requested or needed.

In contrast, a client that supports HTTPS records would connect to `endpoint.example`, using an SNI of `endpoint.example` and comparing it to the TLSA record at `_443._tcp.endpoint.example`. This means that a certificate for `endpoint.example` *is* required, and a certificate for `origin.example` is never used.

---

Is this the intended behavior? It strikes me as rather confusing, if so: an example explicitly demonstrating this would be welcome. Alt-Svc headers and HTTPS records are equivalent in most respects, so such a divergence is worth noting.

**Comment by bemasc** [comment]
> Does this mean that a DANE-compatible client will require distinct certificates depending on whether they use Alt-Svc or HTTPS records to locate the endpoint?

DANE for HTTP is not implemented anywhere, to my knowledge, and [might even be insecure](https://datatracker.ietf.org/doc/html/draft-barnes-dane-uks-00).  I don't think anyone has figured out how DANE would work with Alt-Svc.  This draft doesn't change that.  Also, Alt-Svc is [falling out of favor](https://lists.w3.org/Archives/Public/ietf-http-wg/2022OctDec/0062.html) and may be headed for deprecation.

I don't think this draft should try to address HTTP Alt-Svc.  I suspect the right answer is that DANE and Alt-Svc are not compatible ... but this is a moot point, because nobody uses DANE with HTTP, and Alt-Svc seems to be on its way out.
